name : Crystal.js
brand : cojomojo
description : A lightweight Javascript live/inline form validator.
keyword: Form Validation
url : http://cojomojo.github.io/crystal.js/
imageurl: 
email : cody@functioncreate.com
twitter : functioncreate
github : cojomojo
author: Cody Balos
analytics: 
year: 2014
markdown: kramdown
